backend:
  name: github
  repo: addisonschultz/netlifyCMSBuilder
  branch: master

media_folder: static
public_folder: ./

site_url: https://github.com/addisonschultz/netlifyCMSBuilder
display_url: https://github.com/addisonschultz/netlifyCMSBuilder

slug:
  encoding: "ascii"
  clean_accents: true

collections:
  # Labels
  - name: labels
    label: "Labels"
    label_singular: "Label"
    folder: src/labels
    create: true
    format: json-frontmatter
    extension: json
    slug: "{{artistName}}"
    fields:
      - { name: artistName, label: Artist Name, widget: "string" }
      - { name: image, label: Image, widget: "image" }
      - { name: bio, label: Bio, widget: "text" }
      - name: releases
        label: Releases
        label_singular: release
        widget: "list"
        fields:
          - { name: releaseName, label: Name, widget: "string" }
          - {
              name: releaseDate,
              label: Release Date,
              widget: "datetime",
              dateFormat: "DD.MM.YYYY",
              format: "DD.MM.YYYY",
              timeFormat: false,
            }
          - { name: link, label: Link, widget: "string" }
          - { name: image, label: Image, widget: "image" }
